version: '3.7'

services:
  fastapi:
    container_name: jointrestapi
    environment:
      - RESTAPI_URL=http://127.0.0.1:8000
      - VIEWER_URL=http://127.0.0.1:8050
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --workers 1

  viewer:
    container_name: jointviewer
    environment:
      - RESTAPI_URL=http://host.docker.internal:8000
      - VIEWER_URL=http://host.docker.internal:8050
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8050:8000"
    command: gunicorn -w 1 -b :8000 viewer:server