# Use the official ubuntu image
FROM ubuntu:latest

# Install gmsh and dependencies
RUN apt-get update -y
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install -y python3.10
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-gmsh

# Manually install some packages
RUN pip install dash_vtk
RUN pip install pytest

# Install Python dependencies
ADD requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir gunicorn

COPY src /src

WORKDIR /src

EXPOSE 8000
# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available in Cloud Run.
CMD exec gunicorn --bind 0.0.0.0:8000 --log-level info --workers 1 --threads 8 --timeout 0 viewer:server