version: '3.7'

services:
  fastapi:
    container_name: jointmodel
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --workers 1