# Use the official ubuntu image
FROM python:3.10-slim-buster

# Manually install some packages
RUN pip install dash_vtk
RUN pip install pytest

# Install Python dependencies
ADD requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir gunicorn

COPY src /src

WORKDIR /src

EXPOSE 8000
# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available in Cloud Run.
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "8", "--timeout", "0", "app.app_viewer:server"]