version: '3.7'

services:
  fastapi:
    container_name: jointrest
    environment:
      - RESTAPI_URL=http://127.0.0.1:8020
      - VIEWER_URL=http://127.0.0.1:8050
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-rest
    expose:
      - "8000"
    ports:
      - "8020:8000"
    command: uvicorn app.app_rest:app --host 0.0.0.0 --port 8000 --proxy-headers --workers 1

  viewer:
    depends_on:
      - fastapi
    container_name: jointviewer
    environment:
      - RESTAPI_URL=http://host.docker.internal:8020
      - VIEWER_URL=http://host.docker.internal:8050
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-viewer
    expose:
      - "8000"
    ports:
      - "8050:8000"
    command: gunicorn -w 1 -b :8000 app.app_viewer:server