from pydantic import BaseModel


class Point3D(BaseModel):
    x: float = ...
    y: float = ...
    z: float = ...


class Vector3D(BaseModel):
    x: float = ...
    y: float = ...
    z: float = ...


class Axis3D(BaseModel):
    point: Point3D = ...
    vector: Vector3D = ...


class Tubular(BaseModel):
    name: str = ...
    axis: Axis3D = ...
    diameter: float = ...


class Joint(BaseModel):
    name: str = ...
    tubes: list[Tubular] = ...
    origin: Point3D | None = None
