from pydantic import BaseModel

from .geometry import NpAxis3D, NpPoint3D

class NpTubular(BaseModel):
    name: str = ...
    axis: NpAxis3D = ...
    diameter: float = ...

class NpJoint(BaseModel):
    name: str = ...
    tubes: list[NpTubular] = ...
    origin: NpPoint3D | None = None

class NpModel(BaseModel):
    name: str = ...
    joint: NpJoint = ...
