from .base import NpBaseModel
from .geometry import NpAxis3D, NpPoint3D


class NpTubular(NpBaseModel):
    name: str = ...
    axis: NpAxis3D = ...
    diameter: float = ...


class NpJoint(NpBaseModel):
    name: str = ...
    master: NpTubular = ...
    slaves: list[NpTubular] = ...
    origin: NpPoint3D | None = None


class NpModel(NpBaseModel):
    name: str = ...
    joint: NpJoint = ...
